### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by djmarsu** [koskJan/2048-Java#1]
aika kova sana tehä 2048 :D sulla on vissiin käyttöliittymää vaille valmis? keksitkö ite noi kaikki logiikka jutut vai luitko jostaki :D hyvin jaoteltu eri metodeihin ja muutenkin hyvän näköistä koodia. hyvät testitkin, hyvää illanjatkoa

projekti ladattu 22.11. klo 19

**Comment by djmarsu** [comment]
nii mitä tässä tapahtuu sitten ku "voittaa" :D

**Comment by koskJan** [comment]
Ei ny ihan käyttöliittymää vaille valmis, pitää saada se et peli loppu oikein ja joku score-systeemi :D jos saa sit palikan 2048 nii sit tulee tyylin teksti et "you win" tai vastaava, pitää miettiä viel sitä ja et voiko  peli jatkuu viel sen jälkeen

**Comment by koskJan** [comment]
Niin ja siis katoin aluks githubista 2048 projekteja ja miten ne on toteutettu, mut suurimmasta osasta en ymmärtäny hirveesti. Aikalailla ite koodasin logiikka osiot ja katoin vähän mallia jostain metodeista.

**Comment by djmarsu** [comment]
kovaa :D
